# Generated by Django 4.0.5 on 2022-08-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_zip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='User',
        ),
    ]
