# Generated by Django 4.0.5 on 2022-08-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_portfolio_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
